name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  python-sample:
    uses: ./.github/workflows/python-ci.yml
    with:
      working-directory: samples/python-hello
      python-version: "3.12"
      timeout-minutes: 20
      fail-fast: true
      enable-pip-cache: true

  python-requirements-dev-sample:
    uses: ./.github/workflows/python-ci.yml
    with:
      working-directory: samples/python-requirements-dev
      python-version: "3.12"
      timeout-minutes: 20
      fail-fast: true
      enable-pip-cache: true


  python-requirements-only-sample:
    uses: ./.github/workflows/python-ci.yml
    with:
      working-directory: samples/python-requirements-only
      python-version: "3.12"
      timeout-minutes: 20
      fail-fast: true
      enable-pip-cache: true

  python-compileall-only-sample:
    uses: ./.github/workflows/python-ci.yml
    with:
      working-directory: samples/python-compileall-only
      python-version: "3.12"
      timeout-minutes: 15
      fail-fast: true
      enable-pip-cache: false

  java-sample:
    uses: ./.github/workflows/java-maven-ci.yml
    with:
      working-directory: samples/java-hello
      java-version: "21"
      timeout-minutes: 20
      fail-fast: true
      enable-maven-cache: true
      maven-goals: test

  java-multi-sample:
    uses: ./.github/workflows/java-maven-ci.yml
    with:
      working-directory: samples/java-multi
      java-version: "21"
      timeout-minutes: 20
      fail-fast: true
      enable-maven-cache: true
      maven-goals: test

  docker-sample:
    uses: ./.github/workflows/docker-build.yml
    with:
      context: samples/docker-hello
      file: samples/docker-hello/Dockerfile
      image-name: docker-hello
      tags: local/docker-hello:ci
      push: false
      scan: true
      trivy-severity: CRITICAL
      timeout-minutes: 20

  java-failsafe-sample:
    uses: ./.github/workflows/java-maven-ci.yml
    with:
      working-directory: samples/java-hello
      java-version: "21"
      timeout-minutes: 20
      fail-fast: true
      enable-maven-cache: true
      maven-goals: verify -Pintegration-test
